/** Sample testimonial "scripts" a Top-3 winner can pick from before
 * recording their video testimonial — talking-point cue cards, not
 * word-for-word paragraphs to recite. A read testimonial sounds recited;
 * a winner speaking naturally from a short list of cues, in their own
 * words, sounds like themselves — and still lands in the organizer's
 * required length band once each cue is answered at a normal, unhurried
 * pace. Shown in the TestimonialRecorder video panel, next to the
 * practice-take toggle. */

export type ScriptLengthBand = "3min" | "5min" | "10min";

export interface TestimonialScript {
  id: string;
  lengthBand: ScriptLengthBand;
  title: string;
  /** Roughly how long a natural, unhurried answer to each cue takes —
   * enough cues at that pace to fill the band's target length. */
  prompts: string[];
}

export const SCRIPT_LENGTH_LABEL: Record<ScriptLengthBand, string> = {
  "3min": "~3 minutes (10 scripts)",
  "5min": "~5 minutes (10 scripts)",
  "10min": "~10 minutes (20 scripts)",
};

const THREE_MIN: TestimonialScript[] = [
  {
    id: "3-01", lengthBand: "3min", title: "Quick thank you to the organizer",
    prompts: [
      "Say your name, your rank/belt, and which category you competed in.",
      "Say what you won and which competition tier.",
      "Thank the organizer for putting together a virtual competition you could join from anywhere.",
      "Mention one thing about how it was run that you appreciated.",
      "Say what you'd tell a friend thinking about joining next time.",
    ],
  },
  {
    id: "3-02", lengthBand: "3min", title: "My kata journey, the short version",
    prompts: [
      "Introduce yourself and how long you've trained Goju-ryu.",
      "Say which kata you performed and why you chose it.",
      "Describe one moment during training that stands out.",
      "Say how it felt watching the scores come in.",
      "Close with what this win means for your training going forward.",
    ],
  },
  {
    id: "3-03", lengthBand: "3min", title: "A message to fellow competitors",
    prompts: [
      "Introduce yourself and your category.",
      "Say what you'd tell someone nervous about their first competition.",
      "Share one piece of advice about recording a kata video.",
      "Say something encouraging to everyone who competed alongside you.",
      "End with congratulations to the other winners in your category.",
    ],
  },
  {
    id: "3-04", lengthBand: "3min", title: "Thank you to my sensei",
    prompts: [
      "Introduce yourself and name your sensei/dojo.",
      "Describe one thing your sensei taught you that mattered most for this kata.",
      "Share a specific correction or piece of coaching that helped you improve.",
      "Say how it felt to bring this result back to your dojo.",
      "Thank your sensei directly, by name.",
    ],
  },
  {
    id: "3-05", lengthBand: "3min", title: "Thank you to my family",
    prompts: [
      "Introduce yourself and your category.",
      "Say who in your family supported your training and how.",
      "Describe a moment they helped you — filming, encouraging, or just being patient.",
      "Say what this win means to share with them.",
      "Thank them directly, by name if you'd like.",
    ],
  },
  {
    id: "3-06", lengthBand: "3min", title: "Overcoming nerves on recording day",
    prompts: [
      "Introduce yourself and your category.",
      "Describe how you felt right before you hit record.",
      "Say what helped you calm down or focus.",
      "Share what happened once you actually started your kata.",
      "End with advice for someone else who gets nervous on camera.",
    ],
  },
  {
    id: "3-07", lengthBand: "3min", title: "Why a virtual competition worked for me",
    prompts: [
      "Introduce yourself and your category.",
      "Say what made a virtual/recorded format easier for you than an in-person one.",
      "Describe where and how you set up to record.",
      "Share one surprise — good or challenging — about competing this way.",
      "Say whether you'd choose this format again.",
    ],
  },
  {
    id: "3-08", lengthBand: "3min", title: "What winning this means to me",
    prompts: [
      "Introduce yourself and what you won.",
      "Say what you were hoping for going in.",
      "Describe the moment you found out you placed.",
      "Say what this result changes for you — confidence, goals, next steps.",
      "Thank the organizer and judges briefly.",
    ],
  },
  {
    id: "3-09", lengthBand: "3min", title: "Advice for beginners",
    prompts: [
      "Introduce yourself and how long you've practiced karate.",
      "Say one thing you wish you knew when you started.",
      "Share your best tip for learning a new kata.",
      "Say what keeps you motivated to keep training.",
      "Encourage a beginner watching this to enter next time.",
    ],
  },
  {
    id: "3-10", lengthBand: "3min", title: "My favorite moment from this competition",
    prompts: [
      "Introduce yourself and your category.",
      "Pick one specific moment from preparing or recording that you enjoyed most.",
      "Say why that moment stuck with you.",
      "Connect it to why you love this sport.",
      "Close with thanks to everyone who made the competition possible.",
    ],
  },
];

const FIVE_MIN: TestimonialScript[] = [
  {
    id: "5-01", lengthBand: "5min", title: "My full journey — training to competition day",
    prompts: [
      "Introduce yourself: name, dojo, belt/rank, category.",
      "Say how long you've trained and how you got started in Goju-ryu.",
      "Describe your training routine in the weeks leading up to this competition.",
      "Name the kata you performed and why it was assigned or chosen for your category.",
      "Describe one specific difficulty you had with this kata and how you worked through it.",
      "Walk through recording day — where, when, how many takes.",
      "Describe the moment you found out your result.",
      "Say what's next for your training.",
      "Thank the organizer, your sensei, and your family, briefly, by name.",
    ],
  },
  {
    id: "5-02", lengthBand: "5min", title: "Overcoming a specific challenge",
    prompts: [
      "Introduce yourself and your category.",
      "Describe a real obstacle you faced this season — injury, time, confidence, technique.",
      "Say when you noticed it was holding you back.",
      "Describe what you changed to work through it.",
      "Name someone who helped you through that period.",
      "Describe how that challenge showed up (or didn't) on competition day.",
      "Say how you felt performing despite it.",
      "Reflect on what this taught you about yourself.",
      "Close with advice for someone facing a similar obstacle right now.",
    ],
  },
  {
    id: "5-03", lengthBand: "5min", title: "A message to my dojo",
    prompts: [
      "Introduce yourself and name your dojo/school and sensei.",
      "Describe what training at your dojo is normally like.",
      "Say how your dojo prepared you specifically for this competition.",
      "Name one training partner or senior student who pushed you.",
      "Describe a specific class or session that made a difference.",
      "Say what it felt like representing your dojo in this competition.",
      "Share what you want your dojo-mates to know about the experience.",
      "Say what you hope for your dojo's future competitors.",
      "Thank your dojo directly, by name.",
    ],
  },
  {
    id: "5-04", lengthBand: "5min", title: "A message to future competitors",
    prompts: [
      "Introduce yourself and your category and result.",
      "Say what you wish someone had told you before your first competition.",
      "Describe how you chose and practiced your kata.",
      "Share your approach to recording — environment, timing, number of takes.",
      "Describe how you managed nerves or self-doubt.",
      "Give one concrete tip about the technical side (camera, space, uniform, background).",
      "Give one concrete tip about the mental side (focus, breathing, routine).",
      "Say what surprised you most about the experience.",
      "End with direct encouragement to someone thinking about entering.",
    ],
  },
  {
    id: "5-05", lengthBand: "5min", title: "Behind the scenes of my kata practice",
    prompts: [
      "Introduce yourself and name your kata.",
      "Describe your usual practice space — home, dojo, outdoors.",
      "Walk through how you break the kata down when practicing: stance by stance, section by section.",
      "Describe a mistake you used to make in this kata and how you fixed it.",
      "Say how many times a week, and for how long, you practiced leading into this.",
      "Describe how you used video (recording yourself, watching others) to improve.",
      "Say what part of the kata you're proudest of now.",
      "Describe how practice felt different the week of the actual recording.",
      "Close with what you'll focus on next in your kata training.",
    ],
  },
  {
    id: "5-06", lengthBand: "5min", title: "What Goju-ryu means to me",
    prompts: [
      "Introduce yourself and how long you've studied Goju-ryu specifically.",
      "Say what first drew you to this style over others.",
      "Describe the balance of hard and soft (go and ju) and where you feel it in your own kata.",
      "Share a principle or value from Goju-ryu training that's shaped you outside the dojo.",
      "Describe a teacher or lineage detail that matters to you.",
      "Say how performing this kata for competition changed your relationship with it.",
      "Describe what you felt performing it on camera, alone, versus in a group class.",
      "Reflect on how this art continues to challenge you.",
      "Close with what Goju-ryu means to you today, in one or two sentences.",
    ],
  },
  {
    id: "5-07", lengthBand: "5min", title: "My proudest moment",
    prompts: [
      "Introduce yourself and your category and result.",
      "Set the scene: where and when you found out you placed.",
      "Describe your first reaction, honestly — shock, relief, tears, laughter.",
      "Say who you told first and how they reacted.",
      "Compare this moment to an earlier, harder moment in your training.",
      "Describe why this particular win feels different from anything before it.",
      "Say what you did to celebrate, if anything.",
      "Reflect on what pride in this achievement actually feels like for you.",
      "Close with thanks to whoever made this moment possible.",
    ],
  },
  {
    id: "5-08", lengthBand: "5min", title: "Thanks to everyone who helped",
    prompts: [
      "Introduce yourself and your category and result.",
      "Thank your sensei by name and say specifically what they gave you.",
      "Thank a training partner or senior student and say how they helped.",
      "Thank a family member and describe one concrete thing they did to support you.",
      "Thank whoever helped film or set up your recording.",
      "Thank the organizer for the competition itself.",
      "Thank the referees/judges for their time reviewing your recording.",
      "Say what it means to have this many people behind one performance.",
      "Close with a general thank-you to everyone watching this testimonial.",
    ],
  },
  {
    id: "5-09", lengthBand: "5min", title: "Balancing training with life",
    prompts: [
      "Introduce yourself, your category, and your main daily commitment (school, work, family).",
      "Describe your typical week and where training fits into it.",
      "Say what you had to give up or rearrange to prepare properly.",
      "Describe a specific week that was especially hard to balance.",
      "Say what kept you motivated when it got difficult.",
      "Describe how people around you (family, employer, teachers) supported the balance.",
      "Say what you learned about discipline through this process.",
      "Reflect on whether it felt worth it now that you've placed.",
      "Close with advice for someone else juggling training with a full life.",
    ],
  },
  {
    id: "5-10", lengthBand: "5min", title: "My kata story — why I chose this kata",
    prompts: [
      "Introduce yourself and name the kata you performed.",
      "Say when you first learned this kata and who taught it to you.",
      "Describe what drew you to this particular kata over others.",
      "Share the meaning or history behind the kata, as you understand it.",
      "Describe a technique or sequence within it that you find most difficult.",
      "Describe a technique or sequence you find most satisfying to perform.",
      "Say how your understanding of this kata changed as you prepared for competition.",
      "Describe how it felt to perform it, knowing it would be judged.",
      "Close with what this kata means to you going forward.",
    ],
  },
];

const TEN_MIN: TestimonialScript[] = [
  {
    id: "10-01", lengthBand: "10min", title: "The complete competition journey",
    prompts: [
      "Introduce yourself fully: name, age category, dojo, sensei, belt/rank.",
      "Describe how and when you first started training in karate, and in Goju-ryu specifically.",
      "Describe what made you decide to enter this competition.",
      "Describe the registration process — was it easy, what tier you chose, any questions you had.",
      "Describe your training plan from the day you registered to the recording deadline.",
      "Name the kata you were assigned or chose, and your first impression of it.",
      "Break down how you practiced it: how often, with whom, what you focused on each week.",
      "Describe a specific setback during preparation — an injury, a bad week, a technique you couldn't get right.",
      "Describe how you worked through that setback.",
      "Describe choosing where and how to record — space, lighting, camera, background, uniform.",
      "Walk through recording day itself, including how many takes it took and why.",
      "Describe watching your own recording back before submitting it.",
      "Describe the wait between submitting and finding out your score.",
      "Describe the moment you found out you placed in the Top 3.",
      "Say what this result means for your training and goals going forward.",
      "Close with thanks to your sensei, your family, the organizer, and the judges, each by name if possible.",
    ],
  },
  {
    id: "10-02", lengthBand: "10min", title: "Family support, from start to finish",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how your family first got involved in your karate journey.",
      "Name each family member who played a role and what they specifically did.",
      "Describe a moment early in your training when family support mattered most.",
      "Describe how your family helped during the lead-up to this specific competition.",
      "Describe who filmed your recording, and what that day was like for them too.",
      "Share a funny or memorable moment from filming with family involved.",
      "Describe how your family reacted when you told them your result.",
      "Reflect on what it means to share this achievement with the people who supported it.",
      "Say what you'd want your family to know that you don't usually say out loud.",
      "Describe how you hope to repay or honor that support going forward.",
      "Close with a direct, heartfelt thank-you to your family, by name.",
    ],
  },
  {
    id: "10-03", lengthBand: "10min", title: "My relationship with my sensei",
    prompts: [
      "Introduce yourself and name your sensei and dojo.",
      "Describe how you first met your sensei and what your early lessons were like.",
      "Describe your sensei's teaching style and philosophy.",
      "Share a specific lesson — technical or personal — that has stayed with you.",
      "Describe how your sensei prepared you specifically for this competition's kata.",
      "Recall a correction your sensei gave that changed your performance significantly.",
      "Describe a moment your sensei encouraged you when you doubted yourself.",
      "Describe what your sensei said or did after seeing your competition result.",
      "Reflect on how your relationship with your sensei has grown over the years.",
      "Say what you hope to carry forward from their teaching as you keep training.",
      "Describe what you'd want other students to know about training under your sensei.",
      "Close with a direct, respectful thank-you to your sensei.",
    ],
  },
  {
    id: "10-04", lengthBand: "10min", title: "Mental preparation and focus",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your mindset in the weeks before the recording deadline.",
      "Share any pre-performance routine you use — breathing, visualization, warm-up.",
      "Describe a time nerves or self-doubt got in your way during preparation.",
      "Describe how you talked yourself through that moment.",
      "Describe what focus feels like for you in the seconds right before starting a kata.",
      "Describe a moment during your kata where you had to refocus mid-performance.",
      "Say how recording alone (without an audience) affected your focus, for better or worse.",
      "Describe how you reviewed your own performance afterward without being overly critical.",
      "Reflect on how your mental approach to competition has changed over time.",
      "Share one mental-preparation tip you'd give another competitor.",
      "Close with what mental strength means to you as a martial artist.",
    ],
  },
  {
    id: "10-05", lengthBand: "10min", title: "Overcoming an injury or setback",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe the injury or setback you experienced and when it happened.",
      "Describe how it affected your training and your confidence at the time.",
      "Describe the recovery process — treatment, rest, modified training.",
      "Name anyone who supported you through recovery — medical, family, dojo.",
      "Describe the moment you returned to full training.",
      "Describe how the setback changed the way you approach this kata specifically.",
      "Describe any lingering caution or adjustment you made for the recording itself.",
      "Describe how it felt to perform fully again despite what you'd been through.",
      "Reflect on what this experience taught you about patience and resilience.",
      "Say what you'd tell someone else currently dealing with an injury.",
      "Close with gratitude for being able to compete and place despite the setback.",
    ],
  },
  {
    id: "10-06", lengthBand: "10min", title: "Why karate matters to me",
    prompts: [
      "Introduce yourself and how long you've practiced karate.",
      "Describe what first brought you — or your family — to karate.",
      "Describe what kept you training when the early days got hard or boring.",
      "Share how karate has shaped your discipline outside the dojo — school, work, daily habits.",
      "Share how karate has shaped your confidence or how you carry yourself.",
      "Describe a specific moment karate helped you through something difficult in life.",
      "Describe what you value about Goju-ryu specifically, compared to other styles you know of.",
      "Describe your relationship with kata versus kumite or other aspects of training.",
      "Say what performing this kata for competition added to your understanding of it.",
      "Reflect on how you hope to keep growing in this art.",
      "Describe what you'd want a non-practitioner to understand about why this matters to you.",
      "Close with what karate means to you today, in your own words.",
    ],
  },
  {
    id: "10-07", lengthBand: "10min", title: "A message to the next generation",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your own first competition experience, however small.",
      "Describe how far you've come since then.",
      "Share what you wish an older student had told you when you started.",
      "Describe how you'd explain the value of competing to a younger or newer student.",
      "Describe your approach to preparing a kata, step by step, as advice.",
      "Give practical advice about recording a video submission — setup, retakes, review.",
      "Give practical advice about handling nerves and pressure.",
      "Describe what you'd say to someone who doesn't place this time.",
      "Share what keeps competitors coming back year after year.",
      "Describe the kind of competitor or teacher you hope to become.",
      "Close with direct, encouraging words to the next generation of Goju-ryu students.",
    ],
  },
  {
    id: "10-08", lengthBand: "10min", title: "Detailed thanks to everyone involved",
    prompts: [
      "Introduce yourself and your category and result.",
      "Thank your sensei by name, describing specifically what they taught you for this kata.",
      "Thank a senior student or training partner by name, describing how they pushed you.",
      "Thank each family member involved by name, describing what they specifically did.",
      "Thank whoever helped with filming/technical setup, describing that process.",
      "Thank the competition organizer, describing what stood out about how it was run.",
      "Thank the referees and judges, acknowledging the time they spent reviewing recordings.",
      "Thank any sponsors, dojo-mates, or community members who cheered you on.",
      "Describe what it feels like to realize how many people it took to get here.",
      "Reflect on the responsibility that comes with representing all of them.",
      "Describe how you hope to pay this support forward to someone else.",
      "Close with one last, sincere thank-you to everyone who made this possible.",
    ],
  },
  {
    id: "10-09", lengthBand: "10min", title: "Goju-ryu philosophy in my own words",
    prompts: [
      "Introduce yourself and your rank and years of training.",
      "Explain, in your own words, what 'Goju' (hard-soft) means to you.",
      "Describe where you feel hardness (go) in your own kata performance.",
      "Describe where you feel softness (ju) in your own kata performance.",
      "Share a breathing or Sanchin-related principle that shapes how you train.",
      "Describe how this philosophy shows up outside the dojo, in daily life.",
      "Share a story from your training where this balance really clicked for you.",
      "Describe how preparing this kata for competition deepened your understanding of the style.",
      "Describe what part of Goju-ryu still challenges or humbles you.",
      "Reflect on how your understanding of the style has changed since you started.",
      "Describe what you hope to understand better in the years ahead.",
      "Close with what Goju-ryu's philosophy means to you as a person, not just a competitor.",
    ],
  },
  {
    id: "10-10", lengthBand: "10min", title: "Competition day, play by play",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe the days immediately before your recording deadline.",
      "Describe how you chose the actual day and time to record.",
      "Describe setting up your space — background, lighting, camera position, uniform.",
      "Describe your warm-up routine right before recording.",
      "Describe your first take and what went wrong, if anything.",
      "Describe how many takes you needed and what changed between them.",
      "Describe the take you finally submitted and why you chose it.",
      "Describe reviewing the footage before uploading.",
      "Describe the moment you hit submit.",
      "Describe the waiting period before scores were released.",
      "Close with the moment you found out your result, and how you felt.",
    ],
  },
  {
    id: "10-11", lengthBand: "10min", title: "What's next for me",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how this result changes your short-term training goals.",
      "Describe any new kata or rank you're now working toward.",
      "Describe whether you plan to compete in the next tier or category.",
      "Share any skills — flexibility, power, timing — you now want to focus on.",
      "Describe how you plan to help newer students at your dojo, if at all.",
      "Describe any long-term goals in karate beyond competition — teaching, grading, black belt milestones.",
      "Describe how you'll balance these goals with the rest of your life.",
      "Describe what support you'll need to get there.",
      "Reflect on how this competition experience has shaped those goals.",
      "Describe what success looks like for you a year from now.",
      "Close with your commitment to keep training and competing.",
    ],
  },
  {
    id: "10-12", lengthBand: "10min", title: "Advice for parents of young karateka",
    prompts: [
      "Introduce yourself, your category, and (if relevant) your age or your child's age.",
      "Describe how a parent or guardian first got you — or your child — into karate.",
      "Describe what support looked like at home during training.",
      "Describe how a parent can help without taking over the training itself.",
      "Describe what filming a competition recording is like from a parent's side.",
      "Share advice for handling a child's nerves before a competition.",
      "Share advice for handling disappointment if a child doesn't place.",
      "Describe the value of competition for a young student's confidence and discipline.",
      "Describe what balance looks like between karate and school/other activities.",
      "Reflect on what you'd want parents watching this to know.",
      "Describe the role of the dojo and sensei in supporting families.",
      "Close with encouragement to parents considering signing their child up.",
    ],
  },
  {
    id: "10-13", lengthBand: "10min", title: "My cultural connection to karate",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how you first learned about karate's origins and Okinawan roots.",
      "Describe what learning Japanese/Okinawan terminology has meant to you.",
      "Share how etiquette and respect (rei) show up in your daily training.",
      "Describe a tradition or ritual in your dojo that you value.",
      "Describe how you researched or connected with the history behind your kata.",
      "Share how this cultural understanding shaped how you performed for competition.",
      "Describe what it means to represent this tradition on a global, online competition stage.",
      "Reflect on the responsibility of carrying forward an art with deep history.",
      "Describe what you'd like to learn more about going forward.",
      "Describe how you'd explain this cultural depth to someone new to karate.",
      "Close with what this tradition means to you personally.",
    ],
  },
  {
    id: "10-14", lengthBand: "10min", title: "Comparing this competition to past ones",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe a previous competition you entered, in-person or virtual.",
      "Compare the preparation process between that one and this one.",
      "Compare how nerves felt then versus now.",
      "Describe what you did differently this time based on past experience.",
      "Describe any result or lesson from that earlier competition that shaped you.",
      "Describe how your kata performance has technically improved since then.",
      "Describe how your mindset around winning and losing has changed.",
      "Reflect on how this virtual/recorded format compares to an in-person one.",
      "Describe what you'll carry forward from this experience into the next competition.",
      "Share advice for someone re-entering after a previous disappointing result.",
      "Close with how proud you are of the growth between then and now.",
    ],
  },
  {
    id: "10-15", lengthBand: "10min", title: "A technical breakdown of my kata",
    prompts: [
      "Introduce yourself and name the kata you performed.",
      "Describe the opening sequence and what it demands technically.",
      "Describe the stances used throughout and which one you find hardest.",
      "Describe the breathing pattern you follow through the kata.",
      "Describe a key technique (strike, block, or transition) that defines this kata.",
      "Describe the rhythm — where it's fast, where it's slow and controlled.",
      "Describe how you worked on precision for the judges reviewing your recording.",
      "Describe how you worked on power and focus (kime) at key moments.",
      "Describe the closing sequence and how you aimed to finish strong.",
      "Reflect on what part of the technical performance you're proudest of.",
      "Describe what you'll keep refining technically going forward.",
      "Close with what mastering this kata's technical details has taught you.",
    ],
  },
  {
    id: "10-16", lengthBand: "10min", title: "The mental-health benefits of martial arts",
    prompts: [
      "Introduce yourself and how long you've trained.",
      "Describe your state of mind — stress, confidence, focus — before you started karate.",
      "Describe how regular training changed your stress levels or mood over time.",
      "Describe how preparing for this specific competition affected your mental state.",
      "Share a specific moment training helped you manage anxiety or pressure.",
      "Describe how the discipline of practice translated into other areas of your life.",
      "Describe the role of community — your dojo — in supporting your wellbeing.",
      "Describe how competing, specifically, affected your confidence.",
      "Reflect on how you managed any pressure or self-criticism around the result.",
      "Describe what you'd say to someone using martial arts to cope with a hard period in life.",
      "Describe your plans to keep training for wellbeing, not just competition.",
      "Close with what karate has given you mentally, beyond the medals.",
    ],
  },
  {
    id: "10-17", lengthBand: "10min", title: "A message to the organizer team",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your first impression signing up for this competition.",
      "Describe the registration and information process from your point of view.",
      "Describe what stood out about how categories and kata assignments were handled.",
      "Describe your experience with the recording and submission process.",
      "Describe any communication you received — confirmations, reminders, updates.",
      "Share a specific moment the organizing team's effort was obvious to you.",
      "Describe how it felt to see winners announced and how that was communicated.",
      "Share constructive thoughts on what worked well and what could improve.",
      "Describe why you'd recommend this competition to others.",
      "Reflect on the effort it takes to run something like this for competitors worldwide.",
      "Close with a direct thank-you to the organizer and every volunteer/staff involved.",
    ],
  },
  {
    id: "10-18", lengthBand: "10min", title: "A message to the judges",
    prompts: [
      "Introduce yourself and your category and result.",
      "Acknowledge that judging a recorded kata is different from judging live.",
      "Describe what you tried to make clear for the camera and the judges — angle, framing, pacing.",
      "Describe your understanding of what judges look for: stances, timing, power, precision.",
      "Share your respect for the time and expertise it takes to score fairly.",
      "Describe how it felt waiting for scores you couldn't see being given live.",
      "Describe your reaction to your own score, whatever it was.",
      "Reflect on what feedback (if any) you received and how it helps you improve.",
      "Describe what you'd want judges to know about how competitors experience scoring.",
      "Share appreciation for the referees/judges who volunteer their time for this.",
      "Describe how their scoring motivates you to keep improving technically.",
      "Close with a sincere thank-you to every judge who reviewed your recording.",
    ],
  },
  {
    id: "10-19", lengthBand: "10min", title: "Hopes for the sport's growth",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe what drew you to a virtual/online kata competition format specifically.",
      "Describe who you think this format opens the door for — remote areas, busy schedules, cost.",
      "Share your hopes for how many more competitors could join in future events.",
      "Describe what you'd like to see added or expanded in future competitions.",
      "Describe how you'd encourage your own dojo-mates to take part next time.",
      "Share your thoughts on how virtual competition complements, not replaces, in-person events.",
      "Describe what you hope the karate community worldwide takes from formats like this.",
      "Reflect on your own role in growing interest at your local dojo.",
      "Describe what you'd tell someone organizing a similar event elsewhere.",
      "Share your hopes for where you personally will be competing a few years from now.",
      "Close with your genuine hope for the sport's future growth.",
    ],
  },
  {
    id: "10-20", lengthBand: "10min", title: "Final reflections on this achievement",
    prompts: [
      "Introduce yourself fully and state your category, kata, and result.",
      "Reflect on where you started in your karate journey and where you are now.",
      "Describe the single hardest part of preparing for this competition.",
      "Describe the single most rewarding part of preparing for this competition.",
      "Describe what surprised you most about the whole experience, start to finish.",
      "Reflect on how this result compares to your own expectations going in.",
      "Describe what this achievement means to you beyond the ranking itself.",
      "Describe how you'll remember this moment years from now.",
      "Share what you'd tell your past self, before you started training.",
      "Describe your intentions for continuing to grow in Goju-ryu.",
      "Offer a closing thought to anyone watching who is considering this path.",
      "Close with heartfelt thanks to everyone who made this moment possible.",
    ],
  },
];

export const TESTIMONIAL_SCRIPTS: TestimonialScript[] = [...THREE_MIN, ...FIVE_MIN, ...TEN_MIN];

export function scriptsForBand(band: ScriptLengthBand): TestimonialScript[] {
  return TESTIMONIAL_SCRIPTS.filter((s) => s.lengthBand === band);
}
