/** Sample testimonial scripts a Top-3 winner can pick from before recording
 * their video testimonial.
 *
 * Each script now carries BOTH halves of the organizer's own template:
 *
 *   - `prompts` — the lettered cues (a, b, c...) saying what to cover;
 *   - `script`  — the same thing written out in the first person, on the
 *     participant's behalf, with XXX and ______ left for them to fill in.
 *
 * The written half exists because cue cards alone assume the speaker can
 * compose fluent English on camera under pressure, which is not a fair
 * assumption for a competition whose entrants span many countries and ages.
 * Every script opens with "Hi" and closes with "Thank you", per the
 * organizer's template.
 *
 * They stay editable and copyable everywhere they appear: the picker
 * renders `script` in a selectable textarea with a Copy button, and the
 * downloadable PDF prints the cues and the script side by side, exactly
 * like the organizer's own two-column table. */

export type ScriptLengthBand = "3min" | "5min" | "10min";

export interface TestimonialScript {
  id: string;
  lengthBand: ScriptLengthBand;
  title: string;
  /** Roughly how long a natural, unhurried answer to each cue takes —
   * enough cues at that pace to fill the band's target length. */
  prompts: string[];
  /** The same cues written out on the participant's behalf, one line per
   * element. Blanks are XXX (names) or ______ (everything else). */
  script: string[];
}

export const SCRIPT_LENGTH_LABEL: Record<ScriptLengthBand, string> = {
  "3min": "~3 minutes (10 scripts)",
  "5min": "~5 minutes (10 scripts)",
  "10min": "~10 minutes (20 scripts)",
};

/** Repeated opening block from the organizer's own example — kept identical
 * across scripts so a participant who fills it in once can reuse it. */
const OPEN_BELT = [
  "Hi, My name is XXX, I am a ___________ holder.",
  "I compete in Kata ______________",
  "Gender: _________ - Age group: __________",
  "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
];

const THREE_MIN: TestimonialScript[] = [
  {
    id: "3-01", lengthBand: "3min", title: "Quick thank you to the organizer",
    prompts: [
      "Say your name, your rank/belt, and which category you competed in.",
      "Say what you won and which competition tier.",
      "Thank the organizer for putting together a virtual competition you could join from anywhere.",
      "Mention one thing about how it was run that you appreciated.",
      "Say what you'd tell a friend thinking about joining next time.",
    ],
    script: [
      ...OPEN_BELT,
      "I am very happy to say that I won ________ place in my category.",
      "A big Thanks to the organizer for putting together a virtual competition where I could join from anywhere.",
      "This event was run in a period of ______ weeks times is the one thing that I really appreciated.",
      "I would really encourage my karateka friends to join next time as all the judging score & video were disclose after the winner announcement date - I am really impressed & learn a lot about the fair & square & the disclosure system. Thank you.",
    ],
  },
  {
    id: "3-02", lengthBand: "3min", title: "My kata journey, the short version",
    prompts: [
      "Introduce yourself and how long you've trained Goju-ryu.",
      "Say which kata you performed and why you chose it.",
      "Describe one moment during training that stands out.",
      "Say how it felt watching the scores come in.",
      "Close with what this win means for your training going forward.",
    ],
    script: [
      "Hi, My name is XXX, I have been training Goju-ryu karate-do for the past ______ years.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "because I have confidence I will do better.",
      "This is the Kata my sensei stress a lot which to area to do what & which area must be in this way in order to score.",
      "I surprise watching the judging score & video which was disclose on the winner announcement date.",
      "This win means that I will train harder base on my experience sensei advise more seriously in the training going forward. Thank you.",
    ],
  },
  {
    id: "3-03", lengthBand: "3min", title: "A message to fellow competitors",
    prompts: [
      "Introduce yourself and your category.",
      "Say what you'd tell someone nervous about their first competition.",
      "Share one piece of advice about recording a kata video.",
      "Say something encouraging to everyone who competed alongside you.",
      "End with congratulations to the other winners in your category.",
    ],
    script: [
      ...OPEN_BELT,
      "To anyone who is nervous about their first competition, I want to say that I was nervous too, and the nervous feeling goes away the moment I start my first move.",
      "My advice for the recording is to prepare your space first - clear the floor, check your light, and stand far enough so the camera can see your whole body from head to toe.",
      "To everyone who competed with me, you already won something by having the courage to record and submit.",
      "Congratulations to the other winners in my category, ________ and ________ - you both performed very well and I learn from watching you. Thank you.",
    ],
  },
  {
    id: "3-04", lengthBand: "3min", title: "Thank you to my sensei",
    prompts: [
      "Introduce yourself and name your sensei/dojo.",
      "Describe one thing your sensei taught you that mattered most for this kata.",
      "Share a specific correction or piece of coaching that helped you improve.",
      "Say how it felt to bring this result back to your dojo.",
      "Thank your sensei directly, by name.",
    ],
    script: [
      "Hi, My name is XXX, I train under Sensei XXX at ______________ Dojo.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "The most important thing my sensei taught me for this kata is ______________________, and it is the reason my performance held together on the day.",
      "The correction that helped me most was when my sensei told me ______________________ - after that my ________ became much more stable.",
      "Bringing this result back to my dojo felt very good, because it belongs to the whole dojo and not only to me.",
      "Sensei XXX, thank you very much for your patience and your teaching. Thank you.",
    ],
  },
  {
    id: "3-05", lengthBand: "3min", title: "Thank you to my family",
    prompts: [
      "Introduce yourself and your category.",
      "Say who in your family supported your training and how.",
      "Describe a moment they helped you — filming, encouraging, or just being patient.",
      "Say what this win means to share with them.",
      "Thank them directly, by name if you'd like.",
    ],
    script: [
      ...OPEN_BELT,
      "My family supported my training all the way, especially XXX, who ______________________ for me every week.",
      "On the recording day, XXX helped me by ______________________, and we had to do it ______ times before I was satisfied.",
      "Sharing this win with them means everything to me, because they gave up their own time so I could train.",
      "XXX and XXX, thank you for supporting me from the beginning until today. Thank you.",
    ],
  },
  {
    id: "3-06", lengthBand: "3min", title: "Overcoming nerves on recording day",
    prompts: [
      "Introduce yourself and your category.",
      "Describe how you felt right before you hit record.",
      "Say what helped you calm down or focus.",
      "Share what happened once you actually started your kata.",
      "End with advice for someone else who gets nervous on camera.",
    ],
    script: [
      ...OPEN_BELT,
      "Right before I press the record button, I felt ______________________ - my hands were not steady and my mind was thinking too much.",
      "What helped me calm down was ______________________, and I also reminded myself that I have practiced this kata ______ times already.",
      "Once I started the kata, the nervous feeling disappeared and my body just followed the training.",
      "So my advice is simple - do not fight the nervous feeling, just start your first move and let your training take over. Thank you.",
    ],
  },
  {
    id: "3-07", lengthBand: "3min", title: "Why a virtual competition worked for me",
    prompts: [
      "Introduce yourself and your category.",
      "Say what made a virtual/recorded format easier for you than an in-person one.",
      "Describe where and how you set up to record.",
      "Share one surprise — good or challenging — about competing this way.",
      "Say whether you'd choose this format again.",
    ],
    script: [
      ...OPEN_BELT,
      "This virtual format was easier for me because ______________________ - I did not need to travel and I could compete from my own place.",
      "I recorded at ______________________, using ______________________ as my camera, and I made sure the background was clean and the light was in front of me.",
      "The thing that surprised me was ______________________, which I did not expect at all before I started.",
      "I would definitely choose this format again, and I hope the organizer keeps running it this way. Thank you.",
    ],
  },
  {
    id: "3-08", lengthBand: "3min", title: "What winning this means to me",
    prompts: [
      "Introduce yourself and what you won.",
      "Say what you were hoping for going in.",
      "Describe the moment you found out you placed.",
      "Say what this result changes for you — confidence, goals, next steps.",
      "Thank the organizer and judges briefly.",
    ],
    script: [
      ...OPEN_BELT,
      "I won ________ place, and honestly, going in I was only hoping to ______________________.",
      "The moment I found out I placed, I was at ______________________ and my first reaction was ______________________.",
      "This result changes a lot for me - it gives me the confidence to aim for ______________________ next.",
      "Thank you to the organizer for the opportunity, and thank you to the judges for taking the time to watch and score my recording. Thank you.",
    ],
  },
  {
    id: "3-09", lengthBand: "3min", title: "Advice for beginners",
    prompts: [
      "Introduce yourself and how long you've practiced karate.",
      "Say one thing you wish you knew when you started.",
      "Share your best tip for learning a new kata.",
      "Say what keeps you motivated to keep training.",
      "Encourage a beginner watching this to enter next time.",
    ],
    script: [
      "Hi, My name is XXX, I have been practicing karate for the past ______ years.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "The one thing I wish somebody told me when I started is ______________________.",
      "My best tip for learning a new kata is to break it into small sections and repeat one section until it feels natural, instead of running the whole kata from the beginning every time.",
      "What keeps me motivated is ______________________, and also seeing myself improve little by little.",
      "If you are a beginner watching this, please join next time - you will learn more from one competition than from many months of normal class. Thank you.",
    ],
  },
  {
    id: "3-10", lengthBand: "3min", title: "My favorite moment from this competition",
    prompts: [
      "Introduce yourself and your category.",
      "Pick one specific moment from preparing or recording that you enjoyed most.",
      "Say why that moment stuck with you.",
      "Connect it to why you love this sport.",
      "Close with thanks to everyone who made the competition possible.",
    ],
    script: [
      ...OPEN_BELT,
      "My favourite moment from this whole competition was ______________________.",
      "That moment stuck in my mind because ______________________.",
      "It reminds me why I love this sport - karate is not only about winning, it is about the small moments where you feel your own progress.",
      "Thank you to the organizer, the judges, my sensei and everyone who made this competition possible. Thank you.",
    ],
  },
];

const FIVE_MIN: TestimonialScript[] = [
  {
    id: "5-01", lengthBand: "5min", title: "My full journey — training to competition day",
    prompts: [
      "Introduce yourself: name, dojo, belt/rank, category.",
      "Say how long you've trained and how you got started in Goju-ryu.",
      "Describe your training routine in the weeks leading up to this competition.",
      "Name the kata you performed and why it was assigned or chosen for your category.",
      "Describe one specific difficulty you had with this kata and how you worked through it.",
      "Walk through recording day — where, when, how many takes.",
      "Describe the moment you found out your result.",
      "Say what's next for your training.",
      "Thank the organizer, your sensei, and your family, briefly, by name.",
    ],
    script: [
      "Hi, My name is XXX, I train at ______________ Dojo and I am a ___________ holder.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "I have been training for ______ years, and I started Goju-ryu because ______________________.",
      "In the weeks before this competition, my routine was ______ sessions a week, about ______ hours each time, and I spent most of that time on ______________________.",
      "The kata I performed is ______________, which was ________ for my category, and I felt it suited me because ______________________.",
      "The most difficult part of this kata for me was ______________________ - my ________ was not correct and it kept costing me balance.",
      "I worked through it by ______________________, and after about ______ weeks it finally became stable.",
      "On the recording day I recorded at ______________________, in the ________, and I needed ______ takes before I was satisfied with one.",
      "When I found out my result, I was ______________________ and my first feeling was ______________________.",
      "What is next for me is ______________________, and I want to train more seriously on ______________________.",
      "Thank you to the organizer for running this competition, thank you Sensei XXX for your teaching, and thank you to XXX and XXX in my family for supporting me all the way. Thank you.",
    ],
  },
  {
    id: "5-02", lengthBand: "5min", title: "Overcoming a specific challenge",
    prompts: [
      "Introduce yourself and your category.",
      "Describe a real obstacle you faced this season — injury, time, confidence, technique.",
      "Say when you noticed it was holding you back.",
      "Describe what you changed to work through it.",
      "Name someone who helped you through that period.",
      "Describe how that challenge showed up (or didn't) on competition day.",
      "Say how you felt performing despite it.",
      "Reflect on what this taught you about yourself.",
      "Close with advice for someone facing a similar obstacle right now.",
    ],
    script: [
      ...OPEN_BELT,
      "This season I faced a real problem, which was ______________________.",
      "I first noticed it was holding me back around ______________________, when I realised I could not ______________________ the way I used to.",
      "To work through it I changed ______________________, and I also had to accept that progress would be slower than I wanted.",
      "XXX helped me a lot during that period by ______________________ - without that help I do not think I would have submitted at all.",
      "On the recording day, the problem showed up ______________________, but I had already prepared for it.",
      "Performing despite it felt ______________________, and I am proud that I did not give myself an excuse to stop.",
      "What this taught me about myself is ______________________.",
      "If you are facing the same kind of obstacle right now, my advice is to keep training the parts you still can, and be patient with the parts you cannot. Thank you.",
    ],
  },
  {
    id: "5-03", lengthBand: "5min", title: "A message to my dojo",
    prompts: [
      "Introduce yourself and name your dojo/school and sensei.",
      "Describe what training at your dojo is normally like.",
      "Say how your dojo prepared you specifically for this competition.",
      "Name one training partner or senior student who pushed you.",
      "Describe a specific class or session that made a difference.",
      "Say what it felt like representing your dojo in this competition.",
      "Share what you want your dojo-mates to know about the experience.",
      "Say what you hope for your dojo's future competitors.",
      "Thank your dojo directly, by name.",
    ],
    script: [
      "Hi, My name is XXX, I train at ______________ Dojo under Sensei XXX.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "Training at my dojo is normally ______________________ - we usually start with ______________________ and finish with ______________________.",
      "For this competition, my dojo prepared me by ______________________, which was different from our normal class.",
      "XXX pushed me the most during that period, especially when ______________________.",
      "There was one session on ______________________ that really made the difference for me, because ______________________.",
      "Representing my dojo in this competition felt ______________________, and I was very aware that I was not only performing for myself.",
      "What I want my dojo-mates to know is that the recording is not as frightening as it looks, and the preparation is the same discipline we do every week.",
      "I hope our future competitors from ______________ Dojo will enter in bigger numbers next time.",
      "Thank you to everyone at ______________ Dojo. Thank you.",
    ],
  },
  {
    id: "5-04", lengthBand: "5min", title: "A message to future competitors",
    prompts: [
      "Introduce yourself and your category and result.",
      "Say what you wish someone had told you before your first competition.",
      "Describe how you chose and practiced your kata.",
      "Share your approach to recording — environment, timing, number of takes.",
      "Describe how you managed nerves or self-doubt.",
      "Give one concrete tip about the technical side (camera, space, uniform, background).",
      "Give one concrete tip about the mental side (focus, breathing, routine).",
      "Say what surprised you most about the experience.",
      "End with direct encouragement to someone thinking about entering.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "What I wish somebody had told me before my first competition is ______________________.",
      "I chose my kata because ______________________, and I practiced it ______ times a week for about ______ weeks.",
      "For the recording, I chose ______________________ as my space and recorded in the ________ when the light was best, and I used ______ takes in total.",
      "I managed my nerves by ______________________, and by reminding myself that a retake is allowed.",
      "My technical tip is this - stand far enough back that your whole body including your hands and feet stays inside the frame for the entire kata, and check it by watching one practice take before the real one.",
      "My mental tip is this - do your normal warm-up routine exactly as you do in class, because the familiar routine tells your body that this is not something strange.",
      "What surprised me the most was ______________________.",
      "If you are thinking about entering, please do it - you will not regret it, and you will improve just from the preparation. Thank you.",
    ],
  },
  {
    id: "5-05", lengthBand: "5min", title: "Behind the scenes of my kata practice",
    prompts: [
      "Introduce yourself and name your kata.",
      "Describe your usual practice space — home, dojo, outdoors.",
      "Walk through how you break the kata down when practicing: stance by stance, section by section.",
      "Describe a mistake you used to make in this kata and how you fixed it.",
      "Say how many times a week, and for how long, you practiced leading into this.",
      "Describe how you used video (recording yourself, watching others) to improve.",
      "Say what part of the kata you're proudest of now.",
      "Describe how practice felt different the week of the actual recording.",
      "Close with what you'll focus on next in your kata training.",
    ],
    script: [
      "Hi, My name is XXX, and the kata I performed is ______________.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "My usual practice space is ______________________, which is ______________________ but it is enough for me to work.",
      "When I practice, I break the kata into ______ sections and work on one section at a time, stance by stance, before I put the whole kata together.",
      "The mistake I used to make in this kata was ______________________, and I fixed it by ______________________.",
      "Leading into the competition I practiced ______ times a week, about ______ minutes each session.",
      "I also recorded myself on my phone and watched it back - seeing my own ________ from outside was the fastest way to correct it.",
      "The part of this kata I am proudest of now is ______________________.",
      "In the week of the actual recording, practice felt ______________________ compared to normal weeks.",
      "Next in my kata training, I want to focus on ______________________. Thank you.",
    ],
  },
  {
    id: "5-06", lengthBand: "5min", title: "What Goju-ryu means to me",
    prompts: [
      "Introduce yourself and how long you've studied Goju-ryu specifically.",
      "Say what first drew you to this style over others.",
      "Describe the balance of hard and soft (go and ju) and where you feel it in your own kata.",
      "Share a principle or value from Goju-ryu training that's shaped you outside the dojo.",
      "Describe a teacher or lineage detail that matters to you.",
      "Say how performing this kata for competition changed your relationship with it.",
      "Describe what you felt performing it on camera, alone, versus in a group class.",
      "Reflect on how this art continues to challenge you.",
      "Close with what Goju-ryu means to you today, in one or two sentences.",
    ],
    script: [
      "Hi, My name is XXX, I have been studying Goju-ryu for the past ______ years.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "What first drew me to Goju-ryu instead of another style was ______________________.",
      "Goju means hard and soft, and in my own kata I feel the hard part in ______________________ and the soft part in ______________________.",
      "The value from Goju-ryu training that has shaped me outside the dojo is ______________________.",
      "The teacher who matters most in my line is ______________________, and what I learned from that teaching is ______________________.",
      "Performing this kata for a competition changed my relationship with it, because now I understand ______________________ that I never paid attention to before.",
      "Performing it alone on camera felt very different from a group class - there is nobody beside me to follow, so every timing is my own decision.",
      "This art still challenges me in ______________________, and I do not think that will ever finish.",
      "Today, Goju-ryu means ______________________ to me. Thank you.",
    ],
  },
  {
    id: "5-07", lengthBand: "5min", title: "My proudest moment",
    prompts: [
      "Introduce yourself and your category and result.",
      "Set the scene: where and when you found out you placed.",
      "Describe your first reaction, honestly — shock, relief, tears, laughter.",
      "Say who you told first and how they reacted.",
      "Compare this moment to an earlier, harder moment in your training.",
      "Describe why this particular win feels different from anything before it.",
      "Say what you did to celebrate, if anything.",
      "Reflect on what pride in this achievement actually feels like for you.",
      "Close with thanks to whoever made this moment possible.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "I found out on ______________________, when I was at ______________________.",
      "My honest first reaction was ______________________ - I had to check the announcement again to believe it.",
      "The first person I told was XXX, and the reaction was ______________________.",
      "This moment means more to me because of an earlier time when ______________________, and back then I really thought about stopping.",
      "This win feels different from anything before because ______________________.",
      "To celebrate, I ______________________ - nothing big, but it felt right.",
      "Being proud of this does not feel like showing off, it feels like ______________________.",
      "Thank you to everyone who made this moment possible - Sensei XXX, my family, and the organizer. Thank you.",
    ],
  },
  {
    id: "5-08", lengthBand: "5min", title: "Thanks to everyone who helped",
    prompts: [
      "Introduce yourself and your category and result.",
      "Thank your sensei by name and say specifically what they gave you.",
      "Thank a training partner or senior student and say how they helped.",
      "Thank a family member and describe one concrete thing they did to support you.",
      "Thank whoever helped film or set up your recording.",
      "Thank the organizer for the competition itself.",
      "Thank the judges for their time reviewing your recording.",
      "Say what it means to have this many people behind one performance.",
      "Close with a general thank-you to everyone watching this testimonial.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "Thank you Sensei XXX - what you gave me was not only the technique, it was ______________________.",
      "Thank you XXX, my training partner, for ______________________ even when you had your own training to worry about.",
      "Thank you XXX from my family, for ______________________ - I know it was not convenient.",
      "Thank you XXX for helping me film and set up the recording, and for being patient through ______ takes.",
      "Thank you to the organizer for running this competition and making it possible for people like me to take part from anywhere.",
      "Thank you to all the judges who spent their own time watching and scoring every recording carefully.",
      "It means a lot to realise that one performance of a few minutes actually carries this many people behind it.",
      "And thank you to everyone watching this. Thank you.",
    ],
  },
  {
    id: "5-09", lengthBand: "5min", title: "Balancing training with life",
    prompts: [
      "Introduce yourself, your category, and your main daily commitment (school, work, family).",
      "Describe your typical week and where training fits into it.",
      "Say what you had to give up or rearrange to prepare properly.",
      "Describe a specific week that was especially hard to balance.",
      "Say what kept you motivated when it got difficult.",
      "Describe how people around you (family, employer, teachers) supported the balance.",
      "Say what you learned about discipline through this process.",
      "Reflect on whether it felt worth it now that you've placed.",
      "Close with advice for someone else juggling training with a full life.",
    ],
    script: [
      ...OPEN_BELT,
      "Outside of karate, my main commitment is ______________________, which takes most of my day.",
      "In a typical week, I train on ______________________, usually ______________________, because that is the only time I can protect.",
      "To prepare properly I had to give up ______________________, and rearrange ______________________.",
      "The hardest week was ______________________, when ______________________ happened at the same time as my training.",
      "What kept me going was ______________________.",
      "The people around me supported me by ______________________, and I could not have kept the balance without that.",
      "What I learned about discipline is that it is not about training when you feel strong, it is about training on the days you do not feel like it.",
      "Now that I have placed ________, I can say it was worth every rearrangement.",
      "If you are juggling training with a full life, my advice is to protect one fixed session a week and never move it. Thank you.",
    ],
  },
  {
    id: "5-10", lengthBand: "5min", title: "My kata story — why I chose this kata",
    prompts: [
      "Introduce yourself and name the kata you performed.",
      "Say when you first learned this kata and who taught it to you.",
      "Describe what drew you to this particular kata over others.",
      "Share the meaning or history behind the kata, as you understand it.",
      "Describe a technique or sequence within it that you find most difficult.",
      "Describe a technique or sequence you find most satisfying to perform.",
      "Say how your understanding of this kata changed as you prepared for competition.",
      "Describe how it felt to perform it, knowing it would be judged.",
      "Close with what this kata means to you going forward.",
    ],
    script: [
      "Hi, My name is XXX, and the kata I performed for this competition is ______________.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "I first learned this kata in ________, and it was taught to me by Sensei XXX.",
      "What drew me to this kata over the others is ______________________.",
      "As I understand it, the meaning behind this kata is ______________________.",
      "The most difficult sequence for me is ______________________, because ______________________.",
      "The most satisfying part to perform is ______________________ - when it is correct, you can feel it.",
      "Preparing for competition changed my understanding, because I had to think about ______________________ instead of just remembering the moves.",
      "Performing it knowing that judges would watch every detail felt ______________________.",
      "Going forward, this kata means ______________________ to me. Thank you.",
    ],
  },
];

const TEN_MIN: TestimonialScript[] = [
  {
    id: "10-01", lengthBand: "10min", title: "The complete competition journey",
    prompts: [
      "Introduce yourself fully: name, age category, dojo, sensei, belt/rank.",
      "Describe how and when you first started training in karate, and in Goju-ryu specifically.",
      "Describe what made you decide to enter this competition.",
      "Describe the registration process — was it easy, what tier you chose, any questions you had.",
      "Describe your training plan from the day you registered to the recording deadline.",
      "Name the kata you were assigned or chose, and your first impression of it.",
      "Break down how you practiced it: how often, with whom, what you focused on each week.",
      "Describe a specific setback during preparation — an injury, a bad week, a technique you couldn't get right.",
      "Describe how you worked through that setback.",
      "Describe choosing where and how to record — space, lighting, camera, background, uniform.",
      "Walk through recording day itself, including how many takes it took and why.",
      "Describe watching your own recording back before submitting it.",
      "Describe the wait between submitting and finding out your score.",
      "Describe the moment you found out you placed in the Top 3.",
      "Say what this result means for your training and goals going forward.",
      "Close with thanks to your sensei, your family, the organizer, and the judges, each by name if possible.",
    ],
    script: [
      "Hi, My name is XXX, I am a ___________ holder, I train at ______________ Dojo under Sensei XXX.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier.",
      "I first started karate in ________, when I was ______ years old, and I came into Goju-ryu specifically because ______________________.",
      "What made me decide to enter this competition was ______________________.",
      "The registration itself was ______________________ for me, I chose the ________ Tier, and the only thing I was not sure about at first was ______________________.",
      "From the day I registered until the recording deadline, my plan was ______ sessions a week for ______ weeks, and each week I focused on one thing at a time.",
      "The kata for my category is ______________, and my first impression of it was ______________________.",
      "I practiced it with ______________________, and week by week I worked on ______________________, then ______________________, then ______________________.",
      "During preparation I had a setback - ______________________ - and it happened around ______________________.",
      "I worked through it by ______________________, and by accepting that I had to slow down before I could speed up again.",
      "For the recording, I chose ______________________ as my space, because the floor was ______________________ and the light came from ______________________.",
      "I wore ______________________, and I made sure the background was plain so nothing would distract the judges.",
      "On the recording day itself I needed ______ takes - the first one failed because ______________________, and the one I kept was better because ______________________.",
      "Watching my own recording back before submitting was uncomfortable at first, because I could see every small mistake, but it also showed me that the overall kata was solid.",
      "The wait between submitting and the announcement felt ______________________, and I tried not to think about it too much.",
      "When I found out I placed in the Top 3, I was at ______________________ and I felt ______________________.",
      "For my training going forward, this result means ______________________, and my next goal is ______________________.",
      "Thank you Sensei XXX for your teaching, thank you XXX and XXX in my family, thank you to the organizer for making this competition possible, and thank you to all the judges who reviewed my recording. Thank you.",
    ],
  },
  {
    id: "10-02", lengthBand: "10min", title: "Family support, from start to finish",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how your family first got involved in your karate journey.",
      "Name each family member who played a role and what they specifically did.",
      "Describe a moment early in your training when family support mattered most.",
      "Describe how your family helped during the lead-up to this specific competition.",
      "Describe who filmed your recording, and what that day was like for them too.",
      "Share a funny or memorable moment from filming with family involved.",
      "Describe how your family reacted when you told them your result.",
      "Reflect on what it means to share this achievement with the people who supported it.",
      "Say what you'd want your family to know that you don't usually say out loud.",
      "Describe how you hope to repay or honor that support going forward.",
      "Close with a direct, heartfelt thank-you to your family, by name.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "My family first got involved in my karate journey when ______________________.",
      "XXX played the biggest role by ______________________, XXX helped by ______________________, and XXX supported me by ______________________.",
      "Early in my training there was a moment when ______________________, and without my family I would have stopped there.",
      "In the lead-up to this competition, my family helped by ______________________, including rearranging ______________________ so I could train.",
      "XXX filmed my recording, and that day was long for them too - they had to stand and hold still for ______ takes without complaining.",
      "The funniest moment was when ______________________, and we still laugh about it now.",
      "When I told them my result, XXX reacted by ______________________, and XXX ______________________.",
      "Sharing this achievement with them means more than the placing itself, because they carried the parts nobody sees.",
      "What I do not usually say out loud is ______________________.",
      "Going forward, I hope to repay that support by ______________________.",
      "XXX, XXX and XXX - thank you for everything you did for me. Thank you.",
    ],
  },
  {
    id: "10-03", lengthBand: "10min", title: "My relationship with my sensei",
    prompts: [
      "Introduce yourself and name your sensei and dojo.",
      "Describe how you first met your sensei and what your early lessons were like.",
      "Describe your sensei's teaching style and philosophy.",
      "Share a specific lesson — technical or personal — that has stayed with you.",
      "Describe how your sensei prepared you specifically for this competition's kata.",
      "Recall a correction your sensei gave that changed your performance significantly.",
      "Describe a moment your sensei encouraged you when you doubted yourself.",
      "Describe what your sensei said or did after seeing your competition result.",
      "Reflect on how your relationship with your sensei has grown over the years.",
      "Say what you hope to carry forward from their teaching as you keep training.",
      "Describe what you'd want other students to know about training under your sensei.",
      "Close with a direct, respectful thank-you to your sensei.",
    ],
    script: [
      "Hi, My name is XXX, I train under Sensei XXX at ______________ Dojo.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier, and I placed ________.",
      "I first met Sensei XXX in ________, and my early lessons were ______________________ - I remember being ______________________.",
      "My sensei's teaching style is ______________________, and the philosophy behind it is ______________________.",
      "One lesson that has stayed with me is ______________________, and it applies far outside the dojo.",
      "For this competition's kata, Sensei XXX prepared me by ______________________.",
      "The one correction that changed my performance the most was ______________________ - before that, my ________ was wrong every single time and I could not see it myself.",
      "There was a moment when I doubted myself, around ______________________, and Sensei XXX told me ______________________, which is the reason I kept going.",
      "After seeing my result, my sensei ______________________, and that meant a great deal to me.",
      "Over the years our relationship has grown from ______________________ into ______________________.",
      "What I hope to carry forward from this teaching is ______________________.",
      "To other students thinking about training under Sensei XXX - ______________________.",
      "Sensei XXX, thank you very much for everything you have taught me. Thank you.",
    ],
  },
  {
    id: "10-04", lengthBand: "10min", title: "Mental preparation and focus",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your mindset in the weeks before the recording deadline.",
      "Share any pre-performance routine you use — breathing, visualization, warm-up.",
      "Describe a time nerves or self-doubt got in your way during preparation.",
      "Describe how you talked yourself through that moment.",
      "Describe what focus feels like for you in the seconds right before starting a kata.",
      "Describe a moment during your kata where you had to refocus mid-performance.",
      "Say how recording alone (without an audience) affected your focus, for better or worse.",
      "Describe how you reviewed your own performance afterward without being overly critical.",
      "Reflect on how your mental approach to competition has changed over time.",
      "Share one mental-preparation tip you'd give another competitor.",
      "Close with what mental strength means to you as a martial artist.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "In the weeks before the deadline, my mindset was ______________________ - some days confident, some days not.",
      "My routine before performing is ______________________, then ______________________, and finally ______ deep breaths before I bow.",
      "During preparation, self-doubt got in my way around ______________________, when I kept making the same mistake in ______________________.",
      "I talked myself through it by ______________________, and by reminding myself that one bad session is not the whole training.",
      "In the seconds right before starting a kata, focus for me feels like ______________________ - everything outside the frame disappears.",
      "During my kata I had to refocus at ______________________, because ______________________ almost pulled my attention away.",
      "Recording alone without an audience affected me ______________________ - there is no energy from a crowd, so all the intensity has to come from inside.",
      "Afterwards, I reviewed my own recording by looking for one thing to fix and one thing done well, instead of only hunting for mistakes.",
      "Over time, my mental approach has changed from ______________________ to ______________________.",
      "My one tip for another competitor is to rehearse your routine, not only your kata - the routine is what carries you when the nerves arrive.",
      "For me, mental strength means ______________________. Thank you.",
    ],
  },
  {
    id: "10-05", lengthBand: "10min", title: "Overcoming an injury or setback",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe the injury or setback you experienced and when it happened.",
      "Describe how it affected your training and your confidence at the time.",
      "Describe the recovery process — treatment, rest, modified training.",
      "Name anyone who supported you through recovery — medical, family, dojo.",
      "Describe the moment you returned to full training.",
      "Describe how the setback changed the way you approach this kata specifically.",
      "Describe any lingering caution or adjustment you made for the recording itself.",
      "Describe how it felt to perform fully again despite what you'd been through.",
      "Reflect on what this experience taught you about patience and resilience.",
      "Say what you'd tell someone else currently dealing with an injury.",
      "Close with gratitude for being able to compete and place despite the setback.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "In ________ I suffered ______________________, and it happened while I was ______________________.",
      "It affected my training badly - I could not ______________________ for about ______ weeks, and my confidence dropped even more than my ability.",
      "My recovery involved ______________________, plus rest and a modified training plan where I only worked on ______________________.",
      "XXX supported me through the recovery by ______________________, and ______________________ also helped me a great deal.",
      "The day I returned to full training, I felt ______________________.",
      "The setback changed how I approach this kata - now I pay much more attention to ______________________ before I do anything at full power.",
      "For the recording itself, I still adjusted ______________________ to protect myself.",
      "Performing fully again after all of that felt ______________________, and honestly that feeling was already a win before any result came out.",
      "What this taught me about patience is ______________________.",
      "If you are dealing with an injury right now, I would tell you to train what you still can, follow the recovery properly, and do not compare yourself to where you were before.",
      "I am grateful that I was able to compete at all, and placing ________ on top of that is something I will not forget. Thank you.",
    ],
  },
  {
    id: "10-06", lengthBand: "10min", title: "Why karate matters to me",
    prompts: [
      "Introduce yourself and how long you've practiced karate.",
      "Describe what first brought you — or your family — to karate.",
      "Describe what kept you training when the early days got hard or boring.",
      "Share how karate has shaped your discipline outside the dojo — school, work, daily habits.",
      "Share how karate has shaped your confidence or how you carry yourself.",
      "Describe a specific moment karate helped you through something difficult in life.",
      "Describe what you value about Goju-ryu specifically, compared to other styles you know of.",
      "Describe your relationship with kata versus kumite or other aspects of training.",
      "Say what performing this kata for competition added to your understanding of it.",
      "Reflect on how you hope to keep growing in this art.",
      "Describe what you'd want a non-practitioner to understand about why this matters to you.",
      "Close with what karate means to you today, in your own words.",
    ],
    script: [
      "Hi, My name is XXX, I have practiced karate for the past ______ years.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier, and I placed ________.",
      "What first brought me to karate was ______________________.",
      "In the early days it was hard and sometimes boring, and what kept me training was ______________________.",
      "Karate has shaped my discipline outside the dojo - because of training, I now ______________________ in my daily life.",
      "It has also changed how I carry myself, especially ______________________.",
      "There was a difficult period in my life around ______________________, and karate helped me through it by ______________________.",
      "What I value about Goju-ryu specifically is ______________________, compared with the other styles I have seen.",
      "Between kata and kumite, I am drawn more to ______________________, because ______________________.",
      "Performing this kata for competition added something to my understanding - I realised ______________________.",
      "I hope to keep growing in this art by ______________________.",
      "If somebody has never trained, what I would want them to understand is that karate is not about fighting, it is about ______________________.",
      "Today, karate means ______________________ to me. Thank you.",
    ],
  },
  {
    id: "10-07", lengthBand: "10min", title: "A message to the next generation",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your own first competition experience, however small.",
      "Describe how far you've come since then.",
      "Share what you wish an older student had told you when you started.",
      "Describe how you'd explain the value of competing to a younger or newer student.",
      "Describe your approach to preparing a kata, step by step, as advice.",
      "Give practical advice about recording a video submission — setup, retakes, review.",
      "Give practical advice about handling nerves and pressure.",
      "Describe what you'd say to someone who doesn't place this time.",
      "Share what keeps competitors coming back year after year.",
      "Describe the kind of competitor or teacher you hope to become.",
      "Close with direct, encouraging words to the next generation of Goju-ryu students.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "My own first competition was in ________, and honestly it was ______________________.",
      "Since then I have come a long way - back then I could not ______________________, and now ______________________.",
      "What I wish an older student had told me when I started is ______________________.",
      "If I had to explain the value of competing to a newer student, I would say that competition is the fastest way to find out which parts of your kata you actually own.",
      "My step-by-step approach is this - first learn the sequence, then fix the stances, then fix the timing, then add the power, and only at the end run the whole kata at full speed.",
      "For the video submission - set up your space and light first, do one practice take and watch it, then do your real takes, and always review before you submit.",
      "For nerves and pressure - keep your normal warm-up, breathe slowly before you bow, and remember that everybody recording today feels exactly the same.",
      "If you did not place this time, I would tell you that ______________________, and that the next one is much closer than you think.",
      "What keeps competitors coming back year after year is ______________________.",
      "The kind of competitor and teacher I hope to become is ______________________.",
      "To the next generation of Goju-ryu students - train honestly, enter the competition, and do not wait until you feel ready. Thank you.",
    ],
  },
  {
    id: "10-08", lengthBand: "10min", title: "Detailed thanks to everyone involved",
    prompts: [
      "Introduce yourself and your category and result.",
      "Thank your sensei by name, describing specifically what they taught you for this kata.",
      "Thank a senior student or training partner by name, describing how they pushed you.",
      "Thank each family member involved by name, describing what they specifically did.",
      "Thank whoever helped with filming/technical setup, describing that process.",
      "Thank the competition organizer, describing what stood out about how it was run.",
      "Thank the judges, acknowledging the time they spent reviewing recordings.",
      "Thank any sponsors, dojo-mates, or community members who cheered you on.",
      "Describe what it feels like to realize how many people it took to get here.",
      "Reflect on the responsibility that comes with representing all of them.",
      "Describe how you hope to pay this support forward to someone else.",
      "Close with one last, sincere thank-you to everyone who made this possible.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "Thank you Sensei XXX - for this kata you taught me ______________________, and you kept correcting it until it was right.",
      "Thank you XXX, my senior at the dojo, for pushing me by ______________________ even when I wanted to stop early.",
      "Thank you XXX for ______________________, thank you XXX for ______________________, and thank you XXX for ______________________.",
      "Thank you XXX for helping with the filming - you set up ______________________ and stayed patient through ______ takes.",
      "Thank you to the organizer. What stood out for me was ______________________, and also that the judging scores and videos were disclosed after the winner announcement date.",
      "Thank you to every judge who spent their own time watching and scoring recordings carefully and fairly.",
      "Thank you also to ______________________ and everybody at my dojo who encouraged me along the way.",
      "It is a strange feeling to realise how many people stand behind a performance of only a few minutes.",
      "That also brings a responsibility - when I perform, I am representing all of them, not only myself.",
      "I hope to pay this forward by ______________________ for the next student who needs the same help.",
      "One last sincere thank you to everyone who made this possible. Thank you.",
    ],
  },
  {
    id: "10-09", lengthBand: "10min", title: "Goju-ryu philosophy in my own words",
    prompts: [
      "Introduce yourself and your rank and years of training.",
      "Explain, in your own words, what 'Goju' (hard-soft) means to you.",
      "Describe where you feel hardness (go) in your own kata performance.",
      "Describe where you feel softness (ju) in your own kata performance.",
      "Share a breathing or Sanchin-related principle that shapes how you train.",
      "Describe how this philosophy shows up outside the dojo, in daily life.",
      "Share a story from your training where this balance really clicked for you.",
      "Describe how preparing this kata for competition deepened your understanding of the style.",
      "Describe what part of Goju-ryu still challenges or humbles you.",
      "Reflect on how your understanding of the style has changed since you started.",
      "Describe what you hope to understand better in the years ahead.",
      "Close with what Goju-ryu's philosophy means to you as a person, not just a competitor.",
    ],
    script: [
      "Hi, My name is XXX, I am a ___________ holder with ______ years of training.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier, and I placed ________.",
      "In my own words, Goju means the balance of hard and soft, and to me that means ______________________.",
      "In my own kata, I feel the hardness in ______________________, where the technique has to finish completely.",
      "I feel the softness in ______________________, where forcing it only makes the movement worse.",
      "The breathing principle that shapes my training comes from ______________________, and it teaches me ______________________.",
      "Outside the dojo, this same balance shows up when ______________________.",
      "There was one training session, around ______________________, where this balance really clicked for me, because ______________________.",
      "Preparing this kata for competition deepened my understanding, because the judges look at ______________________, and that forced me to be honest about my own technique.",
      "The part of Goju-ryu that still humbles me is ______________________.",
      "Since I started, my understanding has changed from ______________________ to ______________________.",
      "In the years ahead, I hope to understand ______________________ much better.",
      "As a person, and not only as a competitor, this philosophy means ______________________ to me. Thank you.",
    ],
  },
  {
    id: "10-10", lengthBand: "10min", title: "Competition day, play by play",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe the days immediately before your recording deadline.",
      "Describe how you chose the actual day and time to record.",
      "Describe setting up your space — background, lighting, camera position, uniform.",
      "Describe your warm-up routine right before recording.",
      "Describe your first take and what went wrong, if anything.",
      "Describe how many takes you needed and what changed between them.",
      "Describe the take you finally submitted and why you chose it.",
      "Describe reviewing the footage before uploading.",
      "Describe the moment you hit submit.",
      "Describe the waiting period before scores were released.",
      "Close with the moment you found out your result, and how you felt.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "In the days right before the deadline I was ______________________, and I kept running the kata in my head.",
      "I chose to record on ______________________ at ______________________, because that is when ______________________.",
      "For my space I used ______________________ - plain background, light coming from ______________________, and the camera placed ______________________ so my whole body stayed in frame.",
      "I wore ______________________, clean and properly tied.",
      "My warm-up was exactly the same as in class - ______________________, then ______________________, so my body would not feel that anything was unusual.",
      "My first take went wrong because ______________________.",
      "In total I needed ______ takes, and between them I changed ______________________ and ______________________.",
      "The take I finally submitted was the one where ______________________ - it was not perfect, but it was the most honest performance.",
      "Reviewing the footage before uploading, I noticed ______________________, and I decided it was still the right one to send.",
      "The moment I hit submit I felt ______________________.",
      "The waiting period was ______________________ - I checked the announcement page more times than I want to admit.",
      "When I finally found out my result, I felt ______________________, and I want to remember that feeling for a long time. Thank you.",
    ],
  },
  {
    id: "10-11", lengthBand: "10min", title: "What's next for me",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how this result changes your short-term training goals.",
      "Describe any new kata or rank you're now working toward.",
      "Describe whether you plan to compete in the next tier or category.",
      "Share any skills — flexibility, power, timing — you now want to focus on.",
      "Describe how you plan to help newer students at your dojo, if at all.",
      "Describe any long-term goals in karate beyond competition — teaching, grading, black belt milestones.",
      "Describe how you'll balance these goals with the rest of your life.",
      "Describe what support you'll need to get there.",
      "Reflect on how this competition experience has shaped those goals.",
      "Describe what success looks like for you a year from now.",
      "Close with your commitment to keep training and competing.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "In the short term, this result changes my goals - now I want to ______________________ within the next ______ months.",
      "I am currently working towards ______________________, and my next grading target is ______________________.",
      "For the next competition I plan to enter the ________ Tier, in the ______________________ category.",
      "The skills I want to focus on now are ______________________ and ______________________.",
      "At my dojo I would like to help the newer students by ______________________.",
      "Beyond competition, my long-term goal in karate is ______________________.",
      "Balancing that with the rest of my life will mean ______________________, and I know I will have to protect my training time.",
      "The support I will need is ______________________ from my sensei, and ______________________ from my family.",
      "This competition shaped those goals because it showed me ______________________.",
      "A year from now, success for me looks like ______________________.",
      "Whatever happens, I am committed to keep training and keep competing. Thank you.",
    ],
  },
  {
    id: "10-12", lengthBand: "10min", title: "Advice for parents of young karateka",
    prompts: [
      "Introduce yourself, your category, and (if relevant) your age or your child's age.",
      "Describe how a parent or guardian first got you — or your child — into karate.",
      "Describe what support looked like at home during training.",
      "Describe how a parent can help without taking over the training itself.",
      "Describe what filming a competition recording is like from a parent's side.",
      "Share advice for handling a child's nerves before a competition.",
      "Share advice for handling disappointment if a child doesn't place.",
      "Describe the value of competition for a young student's confidence and discipline.",
      "Describe what balance looks like between karate and school/other activities.",
      "Reflect on what you'd want parents watching this to know.",
      "Describe the role of the dojo and sensei in supporting families.",
      "Close with encouragement to parents considering signing their child up.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category, and I am ______ years old.",
      "It was XXX who first brought me into karate, in ________, because ______________________.",
      "At home, support looked like ______________________ - not pushing, just making it possible.",
      "A parent can help best by ______________________, and by leaving the technical corrections to the sensei.",
      "From a parent's side, filming a competition recording means standing still, holding the camera steady, and repeating it as many times as the child needs without showing frustration.",
      "For a child's nerves before a competition, my advice is ______________________ - do not add extra pressure by talking about winning.",
      "If a child does not place, the best thing to say is ______________________, because the disappointment passes much faster when the effort is recognised.",
      "Competition is valuable for a young student because it builds ______________________ and ______________________ in a way normal class cannot.",
      "The balance with school and other activities means ______________________, and it has to be planned, not left to chance.",
      "What I would want parents watching this to know is ______________________.",
      "The dojo and the sensei also carry part of this - they support the whole family, not only the student.",
      "If you are a parent thinking about signing your child up, please do it - the discipline they gain lasts far longer than any medal. Thank you.",
    ],
  },
  {
    id: "10-13", lengthBand: "10min", title: "My cultural connection to karate",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe how you first learned about karate's origins and Okinawan roots.",
      "Describe what learning Japanese/Okinawan terminology has meant to you.",
      "Share how etiquette and respect (rei) show up in your daily training.",
      "Describe a tradition or ritual in your dojo that you value.",
      "Describe how you researched or connected with the history behind your kata.",
      "Share how this cultural understanding shaped how you performed for competition.",
      "Describe what it means to represent this tradition on a global, online competition stage.",
      "Reflect on the responsibility of carrying forward an art with deep history.",
      "Describe what you'd like to learn more about going forward.",
      "Describe how you'd explain this cultural depth to someone new to karate.",
      "Close with what this tradition means to you personally.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "I first learned about karate's Okinawan roots from ______________________, and it changed how I saw the training.",
      "Learning the Japanese and Okinawan terminology meant ______________________ to me - the words carry the meaning that a translation loses.",
      "Etiquette and respect show up in my daily training when ______________________, and it is not only a formality.",
      "One tradition in my dojo that I value is ______________________.",
      "To connect with the history behind my kata, I ______________________.",
      "That understanding shaped how I performed for the competition, because I stopped treating the kata as a sequence and started treating it as ______________________.",
      "Representing this tradition on a global online stage means ______________________.",
      "There is a responsibility in carrying forward an art with this much history - it is not mine to change casually.",
      "Going forward, I would like to learn more about ______________________.",
      "If somebody new to karate asked me about this cultural depth, I would explain it by saying ______________________.",
      "Personally, this tradition means ______________________ to me. Thank you.",
    ],
  },
  {
    id: "10-14", lengthBand: "10min", title: "Comparing this competition to past ones",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe a previous competition you entered, in-person or virtual.",
      "Compare the preparation process between that one and this one.",
      "Compare how nerves felt then versus now.",
      "Describe what you did differently this time based on past experience.",
      "Describe any result or lesson from that earlier competition that shaped you.",
      "Describe how your kata performance has technically improved since then.",
      "Describe how your mindset around winning and losing has changed.",
      "Reflect on how this virtual/recorded format compares to an in-person one.",
      "Describe what you'll carry forward from this experience into the next competition.",
      "Share advice for someone re-entering after a previous disappointing result.",
      "Close with how proud you are of the growth between then and now.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "Before this, I entered ______________________ in ________, which was ______________________.",
      "The preparation was different - for that one I ______________________, and for this one I ______________________.",
      "The nerves were also different. Back then I felt ______________________, and this time I felt ______________________.",
      "Based on that past experience, this time I changed ______________________.",
      "The lesson from that earlier competition that shaped me most was ______________________.",
      "Technically, my kata has improved since then in ______________________ and ______________________.",
      "My mindset around winning and losing has changed from ______________________ to ______________________.",
      "Comparing the formats, this virtual recorded competition is ______________________ compared with an in-person one, and I think both have their place.",
      "What I will carry forward into the next competition is ______________________.",
      "If you are re-entering after a disappointing result, my advice is that the earlier result is information, not a verdict - use it and enter again.",
      "Looking at the difference between then and now, I am genuinely proud of the growth. Thank you.",
    ],
  },
  {
    id: "10-15", lengthBand: "10min", title: "A technical breakdown of my kata",
    prompts: [
      "Introduce yourself and name the kata you performed.",
      "Describe the opening sequence and what it demands technically.",
      "Describe the stances used throughout and which one you find hardest.",
      "Describe the breathing pattern you follow through the kata.",
      "Describe a key technique (strike, block, or transition) that defines this kata.",
      "Describe the rhythm — where it's fast, where it's slow and controlled.",
      "Describe how you worked on precision for the judges reviewing your recording.",
      "Describe how you worked on power and focus (kime) at key moments.",
      "Describe the closing sequence and how you aimed to finish strong.",
      "Reflect on what part of the technical performance you're proudest of.",
      "Describe what you'll keep refining technically going forward.",
      "Close with what mastering this kata's technical details has taught you.",
    ],
    script: [
      "Hi, My name is XXX, and the kata I performed is ______________.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier, and I placed ________.",
      "The opening sequence demands ______________________, and if the opening is not clean the whole kata looks unsettled.",
      "The stances used through this kata are ______________________, and the hardest one for me is ______________________ because ______________________.",
      "The breathing pattern I follow is ______________________, and it has to match the technique, not the other way around.",
      "The technique that really defines this kata is ______________________.",
      "The rhythm is not flat - it is fast at ______________________ and slow and controlled at ______________________.",
      "For precision, knowing that judges would review the recording frame by frame, I worked on ______________________ and checked it on video.",
      "For power and kime, I focused on ______________________ at the key moments, without losing control of the stance.",
      "The closing sequence is ______________________, and I wanted to finish as strongly as I started.",
      "Technically, the part I am proudest of is ______________________.",
      "Going forward I will keep refining ______________________.",
      "What mastering the details of this kata has taught me is ______________________. Thank you.",
    ],
  },
  {
    id: "10-16", lengthBand: "10min", title: "The mental-health benefits of martial arts",
    prompts: [
      "Introduce yourself and how long you've trained.",
      "Describe your state of mind — stress, confidence, focus — before you started karate.",
      "Describe how regular training changed your stress levels or mood over time.",
      "Describe how preparing for this specific competition affected your mental state.",
      "Share a specific moment training helped you manage anxiety or pressure.",
      "Describe how the discipline of practice translated into other areas of your life.",
      "Describe the role of community — your dojo — in supporting your wellbeing.",
      "Describe how competing, specifically, affected your confidence.",
      "Reflect on how you managed any pressure or self-criticism around the result.",
      "Describe what you'd say to someone using martial arts to cope with a hard period in life.",
      "Describe your plans to keep training for wellbeing, not just competition.",
      "Close with what karate has given you mentally, beyond the medals.",
    ],
    script: [
      "Hi, My name is XXX, I have been training for the past ______ years.",
      "I compete in Kata ______________",
      "Gender: _________ - Age group: __________",
      "In Malaysia Open Virtual Karate-do Kata Competition USD 10 /100/200 Tier, and I placed ________.",
      "Before I started karate, my state of mind was ______________________.",
      "Over time, regular training changed that - now when I finish a session I feel ______________________.",
      "Preparing for this specific competition affected me ______________________, especially in the last ______ weeks.",
      "There was one moment, around ______________________, when training helped me manage real pressure by ______________________.",
      "The discipline of practice carried over into ______________________ in my daily life.",
      "My dojo community also supports my wellbeing, because ______________________.",
      "Competing specifically affected my confidence by ______________________.",
      "Around the result, I managed the pressure and self-criticism by ______________________.",
      "If somebody is using martial arts to cope with a hard period in life, I would say ______________________ - and that showing up for class is already progress.",
      "I plan to keep training for wellbeing and not only for competition, by ______________________.",
      "Beyond any medal, what karate has given me mentally is ______________________. Thank you.",
    ],
  },
  {
    id: "10-17", lengthBand: "10min", title: "A message to the organizer team",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe your first impression signing up for this competition.",
      "Describe the registration and information process from your point of view.",
      "Describe what stood out about how categories and kata assignments were handled.",
      "Describe your experience with the recording and submission process.",
      "Describe any communication you received — confirmations, reminders, updates.",
      "Share a specific moment the organizing team's effort was obvious to you.",
      "Describe how it felt to see winners announced and how that was communicated.",
      "Share constructive thoughts on what worked well and what could improve.",
      "Describe why you'd recommend this competition to others.",
      "Reflect on the effort it takes to run something like this for competitors worldwide.",
      "Close with a direct thank-you to the organizer and every volunteer/staff involved.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "My first impression when I signed up was ______________________.",
      "The registration and information process was ______________________ from my point of view, and I found ______________________ especially clear.",
      "What stood out about the categories and kata assignments was ______________________.",
      "The recording and submission process was ______________________ - the part I appreciated most was ______________________.",
      "I received ______________________ from the organizer, including confirmations and reminders, which helped me keep track of the deadline.",
      "There was one moment when the organizing team's effort was obvious to me - ______________________.",
      "Seeing the winners announced felt ______________________, and I appreciated that the judging score and video were disclosed after the winner announcement date.",
      "What worked really well was ______________________. If I may suggest one improvement, it would be ______________________.",
      "I would recommend this competition to others because ______________________.",
      "Running something like this for competitors all over the world takes an enormous amount of work that most of us never see.",
      "Thank you to the organizer and to every volunteer and staff member involved. Thank you.",
    ],
  },
  {
    id: "10-18", lengthBand: "10min", title: "A message to the judges",
    prompts: [
      "Introduce yourself and your category and result.",
      "Acknowledge that judging a recorded kata is different from judging live.",
      "Describe what you tried to make clear for the camera and the judges — angle, framing, pacing.",
      "Describe your understanding of what judges look for: stances, timing, power, precision.",
      "Share your respect for the time and expertise it takes to score fairly.",
      "Describe how it felt waiting for scores you couldn't see being given live.",
      "Describe your reaction to your own score, whatever it was.",
      "Reflect on what feedback (if any) you received and how it helps you improve.",
      "Describe what you'd want judges to know about how competitors experience scoring.",
      "Share appreciation for the judges who volunteer their time for this.",
      "Describe how their scoring motivates you to keep improving technically.",
      "Close with a sincere thank-you to every judge who reviewed your recording.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "I understand that judging a recorded kata is not the same as judging live - you cannot walk around the competitor or feel the power in the room.",
      "Knowing that, I tried to make things clear for the camera by ______________________, and by keeping my pacing steady so nothing was lost on video.",
      "My understanding is that judges look at stances, timing, power, precision and the overall control, and that every one of those has to hold from the first move to the last.",
      "It takes real expertise and a lot of time to score that fairly across so many recordings, and I respect that.",
      "Waiting for scores I could not see being given live felt ______________________.",
      "When I saw my own score, my reaction was ______________________.",
      "The feedback I received was ______________________, and it helps me because now I know exactly what to work on.",
      "What I would want judges to know is that competitors read every point carefully, and a fair score is taken seriously even when it is not the score we hoped for.",
      "I appreciate very much that the judges give their own time for this.",
      "Their scoring motivates me to keep improving, especially in ______________________.",
      "Thank you sincerely to every judge who reviewed my recording. Thank you.",
    ],
  },
  {
    id: "10-19", lengthBand: "10min", title: "Hopes for the sport's growth",
    prompts: [
      "Introduce yourself and your category and result.",
      "Describe what drew you to a virtual/online kata competition format specifically.",
      "Describe who you think this format opens the door for — remote areas, busy schedules, cost.",
      "Share your hopes for how many more competitors could join in future events.",
      "Describe what you'd like to see added or expanded in future competitions.",
      "Describe how you'd encourage your own dojo-mates to take part next time.",
      "Share your thoughts on how virtual competition complements, not replaces, in-person events.",
      "Describe what you hope the karate community worldwide takes from formats like this.",
      "Reflect on your own role in growing interest at your local dojo.",
      "Describe what you'd tell someone organizing a similar event elsewhere.",
      "Share your hopes for where you personally will be competing a few years from now.",
      "Close with your genuine hope for the sport's future growth.",
    ],
    script: [
      ...OPEN_BELT,
      "I placed ________ in my category.",
      "What drew me to a virtual kata competition specifically was ______________________.",
      "I think this format opens the door for people in remote areas, people with busy schedules, and people who simply cannot afford to travel for a competition.",
      "My hope is that future events will have many more competitors - even ______________________ would already be a big difference.",
      "In future competitions I would like to see ______________________ added or expanded.",
      "I will encourage my own dojo-mates by ______________________, and by showing them that the process is not complicated.",
      "I do not think virtual competition replaces in-person events - it complements them, because ______________________.",
      "What I hope the worldwide karate community takes from formats like this is ______________________.",
      "At my local dojo, my own role in growing interest is ______________________.",
      "To anyone organizing a similar event elsewhere, I would say ______________________.",
      "A few years from now, I hope to be competing at ______________________.",
      "My genuine hope is that this sport keeps growing and reaches many more people. Thank you.",
    ],
  },
  {
    id: "10-20", lengthBand: "10min", title: "Final reflections on this achievement",
    prompts: [
      "Introduce yourself fully and state your category, kata, and result.",
      "Reflect on where you started in your karate journey and where you are now.",
      "Describe the single hardest part of preparing for this competition.",
      "Describe the single most rewarding part of preparing for this competition.",
      "Describe what surprised you most about the whole experience, start to finish.",
      "Reflect on how this result compares to your own expectations going in.",
      "Describe what this achievement means to you beyond the ranking itself.",
      "Describe how you'll remember this moment years from now.",
      "Share what you'd tell your past self, before you started training.",
      "Describe your intentions for continuing to grow in Goju-ryu.",
      "Offer a closing thought to anyone watching who is considering this path.",
      "Close with heartfelt thanks to everyone who made this moment possible.",
    ],
    script: [
      ...OPEN_BELT,
      "The kata I performed is ______________, and I placed ________ in my category.",
      "When I started my karate journey I was ______________________, and today I am ______________________ - the distance between those two is the real result.",
      "The single hardest part of preparing for this competition was ______________________.",
      "The single most rewarding part was ______________________.",
      "What surprised me most about the whole experience, from start to finish, was ______________________.",
      "Compared with my own expectations going in, this result was ______________________.",
      "Beyond the ranking itself, this achievement means ______________________ to me.",
      "Years from now, I will remember this moment as ______________________.",
      "If I could talk to myself before I started training, I would say ______________________.",
      "My intention is to keep growing in Goju-ryu by ______________________.",
      "To anyone watching who is considering this path - start now, train honestly, and enter when the chance comes.",
      "Heartfelt thanks to my sensei, my family, my dojo, the organizer and every judge who made this moment possible. Thank you.",
    ],
  },
];

export const TESTIMONIAL_SCRIPTS: TestimonialScript[] = [...THREE_MIN, ...FIVE_MIN, ...TEN_MIN];

export function scriptsForBand(band: ScriptLengthBand): TestimonialScript[] {
  return TESTIMONIAL_SCRIPTS.filter((s) => s.lengthBand === band);
}

/** One plain-text block per script — what the Copy button puts on the
 * clipboard and what the textarea starts with. */
export function scriptText(script: TestimonialScript): string {
  return script.script.join("\n");
}
